baseurl: https://github.com/jerrychuang97/website1
title: Hugo Tanka Theme Demo
author: Nan Xiao
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: Yongbao Zhuang's website
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Home
      url: /home
      weight: 1
    - name: About
      url: /about
      weight: 2
    - name: GitHub
      url: https://github.com/jerrychuang97
      weight: 3
    - name: Linkedin
      url: https://www.linkedin.com/in/yongbao-zhuang-22189b8b/
      weight: 4
    